name: Build .NET

on:
  push:
    branches:
      - release/8.0
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t custom-dotnet .

      # Run Docker container and execute commands
      - name: Run Tests Inside Docker
        run: |
          docker run custom-dotnet
          "

      # Extract artifacts from the container
      - name: Copy Artifacts
        run: |
          docker cp custom-dotnet:/opt/dotnet/artifacts ./artifacts
          docker stop custom-dotnet
          docker rm custom-dotnet

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts
